// shared/dataclasses.js - Single source of truth for data classes
// Content script version is generated by scripts/build-dataclasses.js

import { CONFIG } from '../bg-components/utils.js';

// Check if current time is during Anthropic's peak hours (weekdays 1pm-7pm GMT)
export function isPeakHours() {
	const now = new Date();
	const day = now.getUTCDay(); // 0=Sun, 6=Sat
	const hour = now.getUTCHours();
	if (day === 0 || day === 6) return false;
	return hour >= 12 && hour < 18;
}

// Model family (Opus/Sonnet/...) for an API model ID; null if unrecognized.
export function modelFamilyFromVersion(modelVersion) {
	const slug = (modelVersion || '').toLowerCase();
	return CONFIG.MODELS.find(family => slug.includes(family.toLowerCase())) || null;
}

// The model claude.ai's picker defaults to for this plan. Pass a null/unknown tier to get
// the tier-agnostic fallback.
export function defaultModelVersionForTier(subscriptionTier) {
	return CONFIG.DEFAULT_MODEL_VERSION_BY_TIER[subscriptionTier] || CONFIG.DEFAULT_MODEL_VERSION;
}

export function defaultModelForTier(subscriptionTier) {
	return modelFamilyFromVersion(defaultModelVersionForTier(subscriptionTier));
}

export class UsageData {
	constructor(data = {}) {
		// Each limit: { percentage, resetsAt } or null
		this.limits = {
			session: data.limits?.session || null,      // five_hour
			weekly: data.limits?.weekly || null,         // seven_day
			sonnetWeekly: data.limits?.sonnetWeekly || null,  // seven_day_sonnet (Max only)
			opusWeekly: data.limits?.opusWeekly || null,       // seven_day_opus (Max only)
			fableWeekly: data.limits?.fableWeekly || null      // weekly_scoped Fable (new format only)
		};
		this.subscriptionTier = data.subscriptionTier || 'claude_free';
		this.extraUsage = data.extraUsage || null;  // { isEnabled, monthlyLimit, usedCredits } (cents)
		this.creditBalance = data.creditBalance ?? null;  // cents (from /credits)
		this.orgId = data.orgId || null;
	}

	static fromAPIResponse(apiResponse, subscriptionTier, creditsResponse = null) {
		const toResetsAt = (isoString) => isoString ? new Date(isoString).getTime() : null;

		// Old top-level format: { utilization, resets_at }
		const parseLimit = (obj) => obj ? {
			percentage: obj.utilization,
			resetsAt: toResetsAt(obj.resets_at)
		} : null;

		// New format: authoritative `limits` array with { kind, percent, resets_at, scope }.
		// Prefer it when present; fall back to the old top-level fields otherwise.
		let limits;
		if (Array.isArray(apiResponse.limits) && apiResponse.limits.length > 0) {
			limits = UsageData.parseNewLimits(apiResponse.limits, toResetsAt);
		} else {
			limits = {
				session: parseLimit(apiResponse.five_hour),
				weekly: parseLimit(apiResponse.seven_day),
				sonnetWeekly: parseLimit(apiResponse.seven_day_sonnet),
				opusWeekly: parseLimit(apiResponse.seven_day_opus)
			};
		}

		// Extra usage: prefer the new `spend` object (replacement for `extra_usage`),
		// fall back to the old `extra_usage` field. Both are in minor units (cents).
		const spend = apiResponse.spend;
		let extraUsage = null;
		if (spend?.enabled) {
			extraUsage = {
				isEnabled: true,
				monthlyLimit: spend.limit?.amount_minor ?? spend.cap?.money?.amount_minor ?? 0,
				usedCredits: spend.used?.amount_minor || 0
			};
		} else if (apiResponse.extra_usage?.is_enabled) {
			extraUsage = {
				isEnabled: true,
				monthlyLimit: apiResponse.extra_usage.monthly_limit,
				usedCredits: apiResponse.extra_usage.used_credits || 0
			};
		}

		// Prepaid credit balance comes from the separate /credits endpoint.
		// (spend.balance is NOT the credit balance — it reads null even when credits exist.)
		const creditBalance = creditsResponse?.amount ?? null;

		return new UsageData({
			limits,
			subscriptionTier,
			extraUsage,
			creditBalance
		});
	}

	// Map the new `limits` array into our fixed internal keys.
	// Scoped weekly limits (weekly_scoped) are keyed by model display name.
	static parseNewLimits(arr, toResetsAt) {
		const scopedKeyByModel = { fable: 'fableWeekly', sonnet: 'sonnetWeekly', opus: 'opusWeekly' };
		const limits = { session: null, weekly: null, sonnetWeekly: null, opusWeekly: null, fableWeekly: null };

		for (const entry of arr) {
			const value = { percentage: entry.percent, resetsAt: toResetsAt(entry.resets_at) };
			if (entry.kind === 'session') {
				limits.session = value;
			} else if (entry.kind === 'weekly_all') {
				limits.weekly = value;
			} else if (entry.kind === 'weekly_scoped') {
				const model = entry.scope?.model?.display_name?.toLowerCase();
				const key = model ? scopedKeyByModel[model] : null;
				if (key) {
					limits[key] = value;
				} else {
					console.warn(`Unknown scoped weekly limit model: ${entry.scope?.model?.display_name}`);
				}
			}
		}

		return limits;
	}

	// Convert % to estimated tokens remaining for a limit
	getEstimatedTokensRemaining(limitKey) {
		const limit = this.limits[limitKey];
		if (!limit) return null;

		let cap = CONFIG.ESTIMATED_CAPS?.[this.subscriptionTier]?.[limitKey];
		if (!cap) return null;

		// During peak hours, session cap is effectively lower
		if (limitKey === 'session' && isPeakHours()) {
			cap = cap / CONFIG.PEAK_SESSION_MULTIPLIER;
		}

		return ((100 - limit.percentage) / 100) * cap;
	}

	// Find which limit will run out first given a message cost
	getLimitingFactor(messageCost) {
		if (!messageCost || messageCost <= 0) return null;

		let minMessages = Infinity;
		let limitingKey = null;

		for (const [key, limit] of Object.entries(this.limits)) {
			if (!limit) continue;

			const tokensRemaining = this.getEstimatedTokensRemaining(key);
			if (tokensRemaining === null) continue;

			const messagesLeft = tokensRemaining / messageCost;
			if (messagesLeft < minMessages) {
				minMessages = messagesLeft;
				limitingKey = key;
			}
		}

		return limitingKey ? { key: limitingKey, messagesLeft: minMessages } : null;
	}

	// Get all active limits for sidebar display
	getActiveLimits() {
		return Object.entries(this.limits)
			.filter(([_, limit]) => limit !== null)
			.map(([key, limit]) => ({ key, ...limit }));
	}

	// Get limits at or above the notification threshold (for notification scheduling)
	getMaxedLimits(threshold = 100) {
		return this.getActiveLimits().filter(limit => limit.percentage >= threshold);
	}

	// Does the server report nothing to draw? claude.ai stopped reporting limits on the free plan:
	// /usage answers 200 with every field null and an empty `limits` array (verified 2026-08-22,
	// including immediately after a message the completion stream *did* report usage for, so this
	// is deliberate for free orgs rather than "no usage yet"). The UI shows a notice instead of an
	// empty box.
	//
	// Not the same as `usageData === null`, which means "not fetched yet" - that stays blank.
	// Extra usage counts as something to draw, so an account with credits but no plan limits keeps
	// its credits bar rather than being told there is nothing.
	hasNoReportedUsage() {
		return this.getActiveLimits().length === 0 && !this.hasExtraUsageConfigured();
	}

	// For chat area: most constraining weekly-type limit (for marker)
	// model: optional model name string (e.g. "Sonnet", "Opus") to filter relevant limits
	getBindingWeeklyLimit(model) {
		const keys = ['weekly'];
		if (model) {
			const m = model.toLowerCase();
			if (m.includes('sonnet')) keys.push('sonnetWeekly');
			if (m.includes('opus')) keys.push('opusWeekly');
			if (m.includes('fable')) keys.push('fableWeekly');
		} else {
			keys.push('sonnetWeekly', 'opusWeekly', 'fableWeekly');
		}


		let candidates = keys
			.map(key => this.limits[key] ? { key, ...this.limits[key] } : null)
			.filter(Boolean);

		if (candidates.length === 0) return null;
		return candidates.reduce((a, b) => a.percentage > b.percentage ? a : b);
	}

	// Session reset info for countdown display
	getSessionResetInfo() {
		const session = this.limits.session;
		if (!session) return null;
		return {
			timestamp: session.resetsAt,
			expired: session.resetsAt <= Date.now()
		};
	}

	// Get effective extra usage remaining (cents)
	getExtraUsageRemaining() {
		if (!this.extraUsage?.isEnabled) return null;
		// Clamped: usedCredits can overshoot monthlyLimit, and a negative remaining
		// would push the displayed percentage past 100.
		const monthlyRemaining = Math.max(0, this.extraUsage.monthlyLimit - this.extraUsage.usedCredits);
		if (this.creditBalance === null) return monthlyRemaining;
		return Math.min(monthlyRemaining, this.creditBalance);
	}

	// Get effective extra usage total (used + remaining) for bar display
	getExtraUsageEffectiveTotal() {
		const remaining = this.getExtraUsageRemaining();
		if (remaining === null) return null;
		return this.extraUsage.usedCredits + remaining;
	}

	// Can this account use extra usage at all? Free accounts can't buy credits,
	// so they never get a credits bar regardless of what /usage reports.
	canUseExtraUsage() {
		return !!this.extraUsage?.isEnabled && this.subscriptionTier !== 'claude_free';
	}

	// Is extra usage active and available?
	hasExtraUsage() {
		return this.canUseExtraUsage() && this.getExtraUsageRemaining() > 0;
	}

	// Is extra usage set up at all? Render gate for the credits bar — independent of
	// remaining budget, so the bar stays visible (at 100%) once credits run out.
	hasExtraUsageConfigured() {
		return this.canUseExtraUsage() && this.getExtraUsageEffectiveTotal() > 0;
	}

	// Is this model funded by credits rather than by the plan? A model that is pay-per-use
	// on the current tier has no plan-scoped weekly limit entry in /usage.
	// Checked for Fable specifically: Sonnet legitimately has no sonnetWeekly entry on
	// non-Max tiers (it's covered by the general weekly limit) and would be misclassified.
	isModelCreditFunded(modelName) {
		if (!modelName?.toLowerCase().includes('fable')) return false;
		return this.limits.fableWeekly === null;
	}

	// Are messages for this model currently billed against credits rather than the plan?
	// Either the model is inherently credit-funded, or the plan limits it draws on are maxed.
	isSpendingCredits(modelName) {
		if (!this.hasExtraUsageConfigured()) return false;
		if (this.isModelCreditFunded(modelName)) return true;
		return this.limits.session?.percentage >= 100 ||
			this.getBindingWeeklyLimit(modelName)?.percentage >= 100;
	}

	toJSON() {
		return {
			limits: this.limits,
			subscriptionTier: this.subscriptionTier,
			extraUsage: this.extraUsage,
			creditBalance: this.creditBalance,
			orgId: this.orgId
		};
	}

	static fromJSON(json) {
		return new UsageData(json);
	}
}

export class ConversationData {
	constructor(data = {}) {
		this.conversationId = data.conversationId;
		this.messages = data.messages || [];

		// Calculated metrics
		this.length = data.length || 0;  // Total tokens in conversation
		this.cost = data.cost || 0;		 // Token cost (with caching possibly considered)
		this.uncachedCost = data.uncachedCost || 0;       // Without caching
		this.futureCost = data.futureCost || 0; // Estimated cost of future messages
		this.uncachedFutureCost = data.uncachedFutureCost || 0; // Estimated future cost without caching
		// Defensive only - the background always populates both before this is rehydrated
		// from JSON, and it has a subscription tier available to pick a better default.
		this.modelVersion = data.modelVersion || CONFIG.DEFAULT_MODEL_VERSION;
		this.model = data.model || modelFamilyFromVersion(this.modelVersion);

		// Cache status
		this.costUsedCache = data.costUsedCache || false;	//Currently unused, since now we show future_cost rather than past cost
		this.conversationIsCachedUntil = data.conversationIsCachedUntil || null;

		// Associated metadata
		this.projectUuid = data.projectUuid || null;
		this.settings = data.settings || {};
		this.lastMessageTimestamp = data.lastMessageTimestamp || null; // Timestamp of the last message in the conversation
		this.lengthIsEstimate = data.lengthIsEstimate || false; // True if length may be inaccurate due to features
		this.orgId = data.orgId || null;
	}

	// Add helper method to check if currently cached
	isCurrentlyCached(currentModelVersion) {
		return this.conversationIsCachedUntil && this.conversationIsCachedUntil > Date.now()
			&& (!currentModelVersion || this.modelVersion === currentModelVersion);
	}

	// Add method to get time until cache expires
	getTimeUntilCacheExpires() {
		if (!this.conversationIsCachedUntil) return null;

		const now = Date.now();
		const diff = this.conversationIsCachedUntil - now;

		if (diff <= 0) return { expired: true, minutes: 0 };

		return {
			expired: false,
			minutes: Math.ceil(diff / (1000 * 60))  // Round up to nearest minute
		};
	}


	// Calculate weighted cost based on model
	getWeightedCost(modelOverride) {
		let model = this.model;
		if (modelOverride) model = modelOverride;
		const weight = CONFIG.MODEL_WEIGHTS[model] ?? CONFIG.FALLBACK_MODEL_WEIGHT;
		return Math.round(this.cost * weight);
	}

	getWeightedFutureCost(modelOverride, modelVersionOverride) {
		let model = this.model;
		if (modelOverride) model = modelOverride;
		const weight = CONFIG.MODEL_WEIGHTS[model] ?? CONFIG.FALLBACK_MODEL_WEIGHT;
		const baseCost = this.isCurrentlyCached(modelVersionOverride) ? this.futureCost : this.uncachedFutureCost;
		return Math.round(baseCost * weight);
	}

	// Check if conversation is expensive
	isExpensive() {
		return this.cost >= CONFIG.WARNING.COST;
	}

	// Check if conversation is long
	isLong() {
		return this.length >= CONFIG.WARNING.LENGTH;
	}

	toJSON() {
		return {
			conversationId: this.conversationId,
			messages: this.messages,
			length: this.length,
			cost: this.cost,
			uncachedCost: this.uncachedCost,
			futureCost: this.futureCost,
			uncachedFutureCost: this.uncachedFutureCost,
			model: this.model,
			modelVersion: this.modelVersion,
			costUsedCache: this.costUsedCache,
			conversationIsCachedUntil: this.conversationIsCachedUntil,
			projectUuid: this.projectUuid,
			settings: this.settings,
			lastMessageTimestamp: this.lastMessageTimestamp,
			lengthIsEstimate: this.lengthIsEstimate,
			orgId: this.orgId
		};
	}

	static fromJSON(json) {
		return new ConversationData(json);
	}
}
